var deepQuestions = [
  "What are your personal goals, and how can I support you in achieving them?",
  "What is one of your fondest childhood memories, and how has it influenced who you are today?",
  "How can I help you manage stress and anxiety in our relationship?",
  "In what ways can we continue to grow and strengthen our relationship?",
  "Can you tell me more about what brings you joy and fulfillment in life?",
  "What is something you've always wanted to do but haven't yet, and how can I help you achieve it?",
  "What is your favorite book or movie, and what does it say about your values and interests?",
  "What accomplishment are you most proud of, and why?",
  "How can I be more mindful of your needs and preferences, even in small ways?",
  "What personal qualities do you value most in yourself and others?",
  "What is one travel destination that you've always dreamed of visiting, and why?",
  "What are some new skills or experiences you'd like to gain, and how can I support you in that process?",
  "What are your hopes and dreams for our future as a couple?",
  "Can you describe a time when you felt heard and understood during a conflict in our relationship?",
  "How do you define happiness, and what can we do to cultivate more of it in our lives together?",
  "How do you explore and nurture your spirituality, and how can I support you in that process?",
  "What are your thoughts and feelings about politics, and how can we engage in healthy conversations about it?",
  "What is your favorite type of cuisine, and can we try cooking a new recipe together sometime?",
  "What was one of the happiest moments of your childhood, and how can we recreate that feeling in our relationship?",
  "What are some of the core values and beliefs that guide your life, and how can I honor and respect them?",
  "Can you tell me about a time when you felt particularly strong or resilient, and what helped you get through it?",
  "What is your favorite type of music, and can we listen to it together and share why we enjoy it?",
  "What do you love about each season, and how can we make the most of those unique experiences together?",
  "What is your favorite thing about yourself, and how can I help you feel more confident and proud of it?",
  "Can you share a quote or saying that is particularly meaningful to you, and what it represents?",
  "What are your thoughts on social media and its impact on our relationship, and how can we navigate it together in a healthy way?",
  "What are some of your biggest aspirations for our life together, and how can we work towards them as a team?",
  "What are some short-term goals you have for our relationship, and how can I support you in achieving them?",
  "How can we work together to cultivate a healthy and positive attitude towards money and finances?",
  "How can we continue to prioritize learning and personal growth in our lives, both as individuals and as a couple?",
  "What is your favorite way to spend a lazy day, and can we plan a day like that together soon?",
  "What are some of your favorite childhood games, and can we play them together as a way to bond and reminisce?",
  "Can you share a favorite TV show or movie that has deep meaning to you, and why it resonates?",
  "What is your favorite way to unwind and relax, and how can I help create a space for that in our relationship?",
  "What is your favorite hobby, and how can we make time for it in our busy lives?",
  "Can you share a personal challenge or struggle you've faced, and how can we work together to support you through it?",
  "What is your favorite type of exercise, and can we try a new workout routine together?",
  "What are some of your favorite memories from our relationship so far, and how can we continue to make more?",
  "How do you envision our future together, and what steps can we take to make that vision a reality?",
  "What is your love language, and how can I show you love and affection in the way that resonates most with you?",
  "What are some ways we can show gratitude and appreciation for each other on a daily basis?",
  "What is your favorite type of art or creative expression, and can we explore it together as a way to bond and connect?",
  "What are your thoughts on spirituality and religion, and how can we respect each other's beliefs and values?",
  "Can you share a dream or aspiration that you've been hesitant to pursue, and how can I encourage and support you in going after it?",
  "What are some ways we can prioritize self-care and mental health in our relationship?",
  "Share a personal problem and ask your partner’s advice on how he or she might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen.",
  "Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you’ve just met.",
  "Complete this sentence: “I wish I had someone with whom I could share ..."",
  
];

var funQuestions = [
  "What are your biggest goals and dreams for the future?",
  "What are your favorite childhood memories?",
  "What are your top five favorite movies or TV shows?",
  "What is your biggest fear, and why?",
  "What is something you've always wanted to learn or try?",
  "What are your favorite hobbies or interests?",
  "What is your most treasured possession, and why?",
  "What is your favorite way to spend a lazy day?",
  "What are some things that make you feel most alive?",
  "What is something you're proud of that you've accomplished in your life?",
  "What is your love language, and how can I show you love in that way?",
  "What is your ideal vacation destination, and why?",
  "What is your favorite type of food, and why?",
  "What is something you're currently reading or learning about?",
  "What is your favorite childhood book or author?",
  "What are some qualities that you admire in other people?",
  "What is something you wish you could change about yourself, and why?",
  "What are your top three bucket list items?",
  "What is something that you're grateful for in your life right now?",
  "What are your favorite type of games or sports to play or watch?",
  "What is your favorite way to spend quality time together?",
  "What is something that always makes you laugh or smile?",
  "What is a skill or talent you have that you're proud of?",
  "What is your favorite season, and why?",
  "What is something you've always wanted to tell me but haven't yet?",
  "What is your favorite song or musician, and why?",
  "What are your top three values in life?",
  "What is your favorite way to celebrate special occasions?",
  "What is your biggest pet peeve, and why?",
  "What is something you would like to do more of in your life?",
  "What is your idea of a perfect day?",
  "What is something you would like to learn from me?",
  "What is your favorite way to unwind after a long day?",
  "What is something that you're looking forward to in the future?",
  "What is your favorite way to show affection or appreciation?",
  "What is your favorite way to stay active or exercise?",
  "What is your favorite way to connect with nature?",
  "What is your favorite way to relax and de-stress?",
  "What is your favorite type of art or creative expression?",
  "What is your favorite way to give back to your community?",
  "What is your favorite type of animal, and why?",
  "What is something you're proud of that you've done for someone else?",
  "What is your favorite way to learn new things?",
  "What is your favorite type of weather, and why?",
  "What is your favorite way to express your creativity?",
  "What is your favorite way to connect with spirituality or religion?",
  "What is something you've always wanted to do but haven't yet?",
  "What is your favorite way to give or receive affection?",
  "What is your favorite way to show support or encouragement?",
  "What is your favorite way to connect with your own emotions?",
  "If you could travel anywhere in the world, where would you go and why?",
  "What is your favorite childhood memory and why does it stand out?",
  "If you could become an expert in any field, what would it be and why?",
  "Would you like to be famous? In what way?",
  "Before making a telephone call, do you ever rehearse what you are going to say? Why?",
  "What would constitute a “perfect” day for you?",
  "When did you last sing to yourself? To someone else?",
  "Name three things you and your partner appear to have in common",
  "For what in your life do you feel most grateful?",
  "If you could change anything about the way you were raised, what would it be?",
  "Take a few minutes and tell your partner your life story in as much detail as possible.",
  "If you could wake up tomorrow having gained any one quality or ability, what would it be?",
  "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
  "Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?",
  "What is the greatest accomplishment of your life?",
  "What do you value most in a friendship?",
  "What is your worst memory?",
  "How close and warm is your family? Do you feel your childhood was happier than most other people’s",
  "What's something you've always wanted to do but haven't had the chance to?",
  "If you could learn any skill, what would it be?",
  "What's your idea of the perfect day?",
  "If you could be any character from a book or movie, who would you be?",
  "What's the best gift you've ever received?",
  "What's your favorite memory from childhood?",
  "If you could travel anywhere in the world, where would you go?",
  "What's one thing you want to accomplish in the next year?",
  "What's your favorite thing about our relationship?",
  "What's something that always cheers you up when you're feeling down?",
  "If you could change one thing about yourself, what would it be?",
  "What's your favorite way to relax?",
  "What's something that you appreciate about each of your family members?",
  "What's one thing that you've always been curious about, but haven't had the chance to explore?",
  "If you could have any job in the world, what would it be?",
  "What's your favorite type of food?",
  "What's something you've accomplished that you're really proud of?",
  "If you could have any superpower, what would it be?",
  "What's something that you're looking forward to in the future?",
  "What's one thing that you love about yourself?",
  "What's something that you're grateful for today?",
  "If you could go back in time and give your younger self one piece of advice, what would it be?",
  "What's your favorite way to spend a lazy day?",
  "What's one thing that you're passionate about?",
  "What's your favorite way to exercise?",
  "If you could have dinner with anyone, living or dead, who would it be?",
  "What's your favorite hobby?",
  "What's something that you've always wanted to learn, but haven't had the time for?",
  "What's one thing that you're proud of that you don't get to talk about often?",
  "If you could switch lives with anyone for a day, who would it be?",
  "What's your favorite thing to do outdoors?",
  "What's one thing that you want to accomplish in your lifetime?",
  "What's your favorite way to unwind after a long day?",
  "What's something that you've learned recently that you found interesting?",
  "If you could relive any moment in your life, what would it be?",
  "What's one thing that you're excited about right now?",
  "What's your favorite way to spend time with family and friends?",
  "What's something that you've always wanted to try, but haven't had the courage to?",
  "If you could live in any time period, what would it be?",
  "What's your favorite way to learn?",
  "What's something that you're looking forward to in the next month?",
  "What's your favorite book or movie?",
  "If you could be any animal, what would it be?",
  "What's something that you're proud of that people might not know about?",
  "What's one thing that you're grateful for today?",
  "What's your favorite way to give back to others?",
  "What's your favorite memory from childhood?",
  "What's your favorite book and why?",
  "What's the biggest risk you've ever taken?",
  "What's the best piece of advice you've ever received?",
  "What's something you're currently learning?",
  "Who is your biggest role model and why?",
  "What are you most grateful for in your life?",
  "What's your idea of a perfect day?",
  "What's something that makes you feel proud of yourself?",
  "What's something you've always wanted to try but haven't yet?",
  "What's your favorite way to relax and unwind?",
  "What's a place you've always wanted to visit?",
  "What's the best gift you've ever given or received?",
  "What's a skill you'd like to learn?",
  "What's your favorite hobby?",
  "What's your favorite movie and why?",
  "What's something you've accomplished that you're proud of?",
  "What's the best vacation you've ever taken?",
  "What's a goal you have for the future?",
  "What's your favorite type of food?",
  "What's a decision you made that you're grateful for?",
  "What's a lesson you've learned that you'll never forget?",
  "What's something you've always wanted to learn more about?",
  "What's something that makes you feel inspired?",
  "What's a fear you've overcome?",
  "What's a place that's special to you and why?",
  "What's the most meaningful gift you've ever received?",
  "What's your idea of a perfect date?",
  "What's a skill or talent you have that not many people know about?",
  "What's something you've been procrastinating on that you want to accomplish?",
  "What's the most adventurous thing you've ever done?",
  "What's something you're proud of in your career?",
  "What's a mistake you've made and what did you learn from it?",
  "What's something you'd like to improve about yourself?",
  "What's your favorite way to spend time with friends and family?",
  "What's a place you've visited that you'll never forget?",
  "What's a challenge you've overcome?",
  "What's something you're looking forward to in the future?",
  "What's a cause you're passionate about and why?",
  "What's your favorite type of music?",
  "What's something you've done that was out of your comfort zone?",
  "What's your favorite way to exercise?",
  "What's a place you'd like to live in the future?",
  "What's your favorite quote and why?",
  "What's a project you're currently working on?",
  "What's a relationship in your life that's important to you?",
  "What's your idea of a perfect weekend?",
  "What's something that always makes you laugh?",
  "What's a place you'd like to travel to and why?",
  "What's a personal accomplishment you're proud of?",
  "What's something you're curious about and want to learn more about?"
];

function getFunQuestion() {
  const randomQuestion = randomItem(funQuestions);
  document.getElementById("question").textContent = randomQuestion;
}

function getDeepQuestion() {
  const randomQuestion = randomItem(deepQuestions);
  document.getElementById("question").textContent = randomQuestion;
}

const randomItem = (arr) => arr.splice((Math.random() * arr.length) | 0, 1);
